[metadata]
name = ckanext-semantictags
version = attr: ckanext.semantictags.__version__
url = https://github.com/SDM-TIB/ckanext-semantictags
author = Philipp D. Rohde
author_email = philipp.rohde@tib.eu
description = A CKAN extension for ontology-backed keywords.
long_description = file: README.md
keywords = CKAN TAGS SEMANTIC ONTOLOGY
license = GNU/GPLv3
license_files = LICENSE
classifiers =
    Development Status :: 4 - Beta
    License :: OSI Approved :: GNU General Public License v3 (GPLv3)
    Programming Language :: Python :: 3 :: Only

[options]
include_package_data = True
packages = find:
python_requires = >=3.8

[options.packages.find]
exclude =
    contrib
    docs
    tests*

[extract_messages]
keywords = translate isPlural
add_comments = TRANSLATORS:
output_file = ckanext/semantictags/i18n/ckanext-semantictags.pot
width = 80

[init_catalog]
domain = ckanext-semantictags
input_file = ckanext/semantictags/i18n/ckanext-semantictags.pot
output_dir = ckanext/semantictags/i18n

[update_catalog]
domain = ckanext-semantictags
input_file = ckanext/semantictags/i18n/ckanext-semantictags.pot
output_dir = ckanext/semantictags/i18n

[compile_catalog]
domain = ckanext-semantictags
directory = ckanext/semantictags/i18n
statistics = true
